# Generated by Django 3.2.18 on 2023-06-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230521_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Подтверждение регистрации', 'verbose_name_plural': 'Подтверждения регистрации'},
        ),
    ]
