# Generated by Django 3.2.18 on 2024-02-11 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='акт-ван?'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.SmallIntegerField(choices=[(1, 'жалоба'), (2, 'предложение'), (3, 'пожелание'), (4, 'вопрос'), (5, 'удаление аккаунта'), (0, 'Other')], default=0, verbose_name='тема')),
                ('content', models.TextField(verbose_name='содержание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'не просмотрено'), (1, 'просмотрено'), (2, 'отклонено'), (3, 'в работе'), (4, 'отработано')], default=0, verbose_name='статус')),
                ('answer', models.TextField(verbose_name='ответ')),
                ('answered', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='обращающийся')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
