# Generated by Django 3.2.18 on 2024-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240211_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-id',), 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='answered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='реализовано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='topic',
            field=models.SmallIntegerField(choices=[(0, 'обращение вне тем'), (1, 'жалоба'), (2, 'предложение'), (3, 'пожелание'), (4, 'вопрос'), (5, 'заявка на удаление аккаунта')], verbose_name='тема'),
        ),
    ]
