# Generated by Django 3.2.18 on 2023-05-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('id',), 'verbose_name': 'basket item', 'verbose_name_plural': 'basket items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('id',), 'verbose_name': 'Категории', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=True, verbose_name='Наличие в продаже'),
        ),
    ]
